/**
 * Legacy `CLOUD_ERRORS`, verbatim (cloud/main.js). Thrown as plain strings so Parse answers
 * `{ code: 141, error: '<STRING>' }`. Spelling is contract: ORDER_FULLFILLED and
 * USER_DOES_NOT_EXISTS are misspelled on purpose, and both PARAMS_MISSING and MISSING_PARAMS exist.
 */
export const CLOUD_ERRORS = {
  USER_UNAUTHENTICATED: 'USER_UNAUTHENTICATED',
  USER_UNAUTHORIZED: 'USER_UNAUTHORIZED',
  FILE_NAME_MISSING: 'FILE_NAME_MISSING',
  PARAMS_MISSING: 'PARAMS_MISSING',
  SEND_PUSH_NOTIFICATION_PARAMS_MISSING: 'SEND_PUSH_NOTIFICATION_PARAMS_MISSING',
  PROCESS_PAYMENT_PARAMS_MISSING: 'PROCESS_PAYMENT_PARAMS_MISSING',
  SAVE_PAYMENT_PARAMS_MISSING: 'SAVE_PAYMENT_PARAMS_MISSING',
  LOGIN_WITH_GOOGLE_PARAMS_MISSING: 'LOGIN_WITH_GOOGLE_PARAMS_MISSING',
  LOGIN_WITH_FACEBOOK_PARAMS_MISSING: 'LOGIN_WITH_FACEBOOK_PARAMS_MISSING',
  LOGIN_WITH_APPLE_PARAMS_MISSING: 'LOGIN_WITH_APPLE_PARAMS_MISSING',
  VERIFY_PHONE_PARAMS_MISSING: 'VERIFY_PHONE_PARAMS_MISSING',
  VERIFY_PHONE_ERROR: 'VERIFY_PHONE_ERROR',
  DRIVER_RATING_PARAMS_MISSING: 'DRIVER_RATING_PARAMS_MISSING',
  LOGIN_STAFF_PARAMS_MISSING: 'LOGIN_STAFF_PARAMS_MISSING',
  USER_DOES_NOT_EXISTS: 'USER_DOES_NOT_EXISTS',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  PROMO_EXISTS: 'PROMO_EXISTS',
  MISSING_PARAMS: 'MISSING_PARAMS',
  USER_PUSH_TOKEN_MISSING: 'USER_PUSH_TOKEN_MISSING',
  STORE_DISABLED: 'STORE_DISABLED',
  DRIVER_DISABLED: 'DRIVER_DISABLED',
  FAILED_TO_PROCESS_PAYMENT: 'FAILED_TO_PROCESS_PAYMENT',
  ORDER_CANCELED: 'ORDER_CANCELED',
  ORDER_FULLFILLED: 'ORDER_FULLFILLED',
  DRIVER_DISCONNECTED: 'DRIVER_DISCONNECTED',
  EMAIL_MISSING: 'EMAIL_MISSING',
  PHONE_NUMBER_USED: 'PHONE_NUMBER_USED',
  DISTANCE_ERROR: 'DISTANCE_ERROR',
  // Not in legacy: the admin guards (D-24). Thrown the same way, as 141 + string.
  ADMIN_REQUIRED: 'ADMIN_REQUIRED',
  SELF_NOT_ALLOWED: 'SELF_NOT_ALLOWED',
  NOT_STAFF_ACCOUNT: 'NOT_STAFF_ACCOUNT',
} as const;
